#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import re
text_type = str
def run(bk):

    print("\nExercising: bk.text_iter()")
    for (id, href) in bk.text_iter():
        print(id, href)

    print("\nExercising: bk.selected_iter()")
    for (id_type, id) in bk.selected_iter():
        if id_type == "manifest":
            href = bk.id_to_href(id, ow=None)
            mime = bk.id_to_mime(id, ow=None)
            print(id_type, id, href, mime)

            html = bk.readfile(id) #чтение файла в html
            if not isinstance(html, text_type): #проверка на формат str
                html = text_type(html, 'utf-8') #перевод формата в 'utf-8'
            html_orig = html #копирование html_orig

            html = re.sub(r'([А-Яа-яёЁ]+)ъ\b', r'\1', html)
            html = re.sub('ъ', '', html)
            html = re.sub('ъ.', '.', html)
            html = re.sub('ъ,', ',', html)
            html = re.sub('ъ-', '-', html)
            html = re.sub('ъ:', ':', html)
            html = re.sub('ъ"', '"', html)
            html = re.sub('ъ!', '!', html)
            html = re.sub('ъ;', ';', html)
            html = re.sub('ъ\n', '\n', html)

            html = re.sub('Ъ', '', html)
            html = re.sub('Ъ.', '.', html)
            html = re.sub('Ъ,', ',', html)
            html = re.sub('Ъ-', '-', html)
            html = re.sub('Ъ:', ':', html)
            html = re.sub('Ъ"', '"', html)
            html = re.sub('Ъ!', '!', html)
            html = re.sub('Ъ;', ';', html)
            html = re.sub('Ъ\n', '\n', html)

            html = re.sub('ѣ', 'е', html)
            html = re.sub('θ', 'ф', html)
            html = re.sub('і', 'и', html)
            html = re.sub('Ѣ', 'Е', html)
            html = re.sub('І', 'И', html)
            html = re.sub('Θ', 'Ф', html)

            html = re.sub(' придти ', ' прийти ', html)
            html = re.sub(' придти, ', ' прийти, ', html)
            html = re.sub(' придти.', ' прийти.', html)
            html = re.sub(' Придти ', ' Прийти ', html)
            html = re.sub(' Придти, ', ' Прийти, ', html)

            html = re.sub('черезчур ', 'чересчур ', html)
            html = re.sub('черезчур, ', 'чересчур, ', html)
            html = re.sub('черезчур.', 'чересчур.', html)
            html = re.sub('Черезчур ', 'Чересчур ', html)
            html = re.sub('Черезчур, ', 'Чересчур, ', html)

            html = re.sub(' подле ', ' возле ', html)
            html = re.sub(' подле, ', ' возле, ', html)
            html = re.sub(' подле.', ' возле.', html)
            html = re.sub('Подле ', 'Возле ', html)
            html = re.sub('Подле, ', 'Возле, ', html)

            html = re.sub(' ужь ', ' уж ', html)
            html = re.sub(' ужь, ', ' уж, ', html)
            html = re.sub(' ужь.', ' уж.', html)
            html = re.sub(' Ужь ', ' Уж ', html)
            html = re.sub(' Ужь, ', ' Уж, ', html)

            html = re.sub(' ея ', ' ее ', html)
            html = re.sub(' ея, ', ' ее, ', html)
            html = re.sub(' ея.', ' ее.', html)
            html = re.sub('Ея ', 'Ее ', html)
            html = re.sub('Ея, ', 'Ее, ', html)
            html = re.sub(' нея ', ' нее ', html)
            html = re.sub(' нея, ', ' нее, ', html)
            html = re.sub(' нея.', ' нее.', html)
            html = re.sub(' Нея ', ' Нее ', html)
            html = re.sub(' Нея, ', ' Нее, ', html)

            html = re.sub(' оне ', ' они ', html)
            html = re.sub(' оне, ', ' они, ', html)
            html = re.sub(' оне.', ' они.', html)
            html = re.sub('Оне ', 'Они ', html)
            html = re.sub('Оне, ', 'Они, ', html)

            html = re.sub(' разс', ' расс', html)
            html = re.sub('Разс', 'Расс', html)
            html = re.sub(' безс', ' бесс', html)
            html = re.sub('Безс', 'Бесс', html)
            html = re.sub(' безп', ' бесп', html)
            html = re.sub('Безп', 'Бесп', html)

            html = re.sub('каго ', 'кого ', html)
            html = re.sub('каго, ', 'кого, ', html)
            html = re.sub('каго.', 'кого.', html)
            html = re.sub('наго ', 'ного ', html)
            html = re.sub('наго, ', 'ного, ', html)
            html = re.sub('наго.', 'ного.', html)
            html = re.sub('баго ', 'бого ', html)
            html = re.sub('баго, ', 'бого, ', html)
            html = re.sub('баго.', 'бого.', html)
            html = re.sub('маго ', 'мого ', html)
            html = re.sub('маго, ', 'мого, ', html)
            html = re.sub('маго.', 'мого.', html)
            html = re.sub('лаго ', 'лого ', html)
            html = re.sub('лаго, ', 'лого, ', html)
            html = re.sub('лаго.', 'лого.', html)
            html = re.sub('таго ', 'того ', html)
            html = re.sub('таго, ', 'того, ', html)
            html = re.sub('таго.', 'того.', html)
            html = re.sub('хаго ', 'хого ', html)
            html = re.sub('хаго, ', 'хого, ', html)
            html = re.sub('хаго.', 'хого.', html)
            html = re.sub('раго ', 'рого ', html)
            html = re.sub('раго, ', 'рого, ', html)
            html = re.sub('раго.', 'рого.', html)
            html = re.sub('ваго ', 'вого ', html)
            html = re.sub('ваго, ', 'вого, ', html)
            html = re.sub('ваго.', 'вого.', html)
            html = re.sub('даго ', 'дого ', html)
            html = re.sub('даго, ', 'дого, ', html)
            html = re.sub('даго.', 'дого.', html)
            html = re.sub('гаго ', 'гого ', html)
            html = re.sub('гаго, ', 'гого, ', html)
            html = re.sub('гаго.', 'гого.', html)
            html = re.sub('щаго ', 'щего ', html)
            html = re.sub('щаго, ', 'щего, ', html)
            html = re.sub('щаго.', 'щего.', html)
            html = re.sub('няго ', 'него ', html)
            html = re.sub('няго, ', 'него, ', html)
            html = re.sub('няго.', 'него.', html)
            html = re.sub('шаго ', 'шего ', html)
            html = re.sub('шаго, ', 'шего, ', html)
            html = re.sub('шаго.', 'шего.', html)
            html = re.sub('чаго ', 'чего ', html)
            html = re.sub('чаго, ', 'чего, ', html)
            html = re.sub('чаго.', 'чего.', html)
            html = re.sub('жаго ', 'жего ', html)
            html = re.sub('жаго, ', 'жего, ', html)
            html = re.sub('жаго.', 'жего.', html)
            html = re.sub('щияся ', 'щиеся ', html)
            html = re.sub('щияся, ', 'щиеся, ', html)
            html = re.sub('щияся.', 'щиеся.', html)
            html = re.sub('шияся ', 'шиеся ', html)
            html = re.sub('шияся, ', 'шиеся, ', html)
            html = re.sub('шияся.', 'шиеся.', html)
            html = re.sub('ныя ', 'ные ', html)
            html = re.sub('ныя, ', 'ные, ', html)
            html = re.sub('ныя.', 'ные.', html)
            html = re.sub('мыя ', 'мые ', html)
            html = re.sub('мыя, ', 'мые, ', html)
            html = re.sub('мыя.', 'мые.', html)
            html = re.sub('рыя ', 'рые ', html)
            html = re.sub('рыя, ', 'рые, ', html)
            html = re.sub('рыя.', 'рые.', html)
            html = re.sub('выя ', 'вые ', html)
            html = re.sub('выя, ', 'вые, ', html)
            html = re.sub('выя.', 'вые.', html)
            html = re.sub('зыя ', 'зые ', html)
            html = re.sub('зыя, ', 'зые, ', html)
            html = re.sub('зыя.', 'зые.', html)
            html = re.sub('тыя ', 'тые ', html)
            html = re.sub('тыя, ', 'тые, ', html)
            html = re.sub('тыя.', 'тые.', html)
            html = re.sub('лыя ', 'лые ', html)
            html = re.sub('лыя, ', 'лые, ', html)
            html = re.sub('лыя.', 'лые.', html)
            html = re.sub('ския ', 'ские ', html)
            html = re.sub('ския, ', 'ские, ', html)
            html = re.sub('ския.', 'ские.', html)

            html = re.sub('такия', 'такие', html)
            html = re.sub('оффициал', 'официал', html)
            html = re.sub('прочия', 'прочие', html)
            html = re.sub('великия', 'великие', html)
            html = re.sub('всякия', 'всякие', html)
            html = re.sub('такия', 'такие', html)
            html = re.sub('ще-бы', 'ще бы', html)
            html = re.sub('сли-б', 'сли б', html)
            html = re.sub('ысокия', 'ысокие', html)
            html = re.sub('третьяго', 'третьего', html)
            html = re.sub('каждаго', 'каждого', html)
            html = re.sub(' мало по малу ', ' мало-помалу ', html)
            html = re.sub('ольшия', 'ольшие', html)
            html = re.sub('другия', 'другие', html)
            html = re.sub('ерния ', 'ерние ', html)
            html = re.sub('овидимому ', 'о-видимому, ', html)
            html = re.sub('чорт', 'черт', html)
            html = re.sub('террасс', 'террас', html)
            html = re.sub('последния', 'последние', html)
            html = re.sub('аваллер', 'авалер', html)
            html = re.sub('десятаго', 'десятого', html)
            html = re.sub('новичек', 'новичок', html)
            html = re.sub('шопот', 'шепот', html)
            html = re.sub('галлер', 'галер', html)
            html = re.sub('ладкия', 'ладкие', html)
            html = re.sub('де-ж ', 'де ж ', html)
            html = re.sub('езполез', 'есполез', html)
            html = re.sub('голыя', 'голые', html)
            html = re.sub('разсуд', 'рассуд', html)
            html = re.sub('как-будто', 'как будто', html)
            html = re.sub('впродолжение', 'в продолжение', html)
            html = re.sub('Впродолжение', 'В продолжение', html)
            html = re.sub('-ли,', ' ли,', html)
            html = re.sub('Голыя', 'Голые', html)
            html = re.sub('если-б', 'если б', html)
            html = re.sub('дальнейшия', 'дальнейшие', html)
            html = re.sub('Многия', 'Многие', html)
            html = re.sub('многия', 'многие', html)
            html = re.sub('безчисл', 'бесчисл', html)
            html = re.sub('безконеч', 'бесконеч', html)
            html = re.sub('однех', 'одних', html)
            html = re.sub('-же ', ' же ', html)
            html = re.sub('втупик', 'в тупик', html)
            html = re.sub('днакож', 'днако ж', html)
            html = re.sub('-ли ', ' ли ', html)
            html = re.sub('-ж ', ' ж ', html)
            html = re.sub('слиб', 'сли б', html)
            html = re.sub('стоящия', 'стоящие', html)
            html = re.sub('корридор', 'коридор', html)
            html = re.sub('новыя', 'новые', html)
            html = re.sub('широкия', 'широкие', html)
            html = re.sub('передния', 'передние', html)
            html = re.sub(' рости ', ' расти ', html)
            html = re.sub('чужия', 'чужие', html)
            html = re.sub('нынешния', 'нынешние', html)
            html = re.sub('девятаго', 'девятого', html)
            html = re.sub('прежняго', 'прежнего', html)
            html = re.sub('глубокия', 'глубокие', html)
            html = re.sub('няньчи', 'нянчи', html)
            html = re.sub(' одне.', ' одни.', html)
            html = re.sub('возст', 'восст', html)
            html = re.sub('решотк', 'решетк', html)
            html = re.sub('танцовал', 'танцевал', html)
            html = re.sub(' нея,', ' нее,', html)
            html = re.sub('что-ж', 'что ж', html)

            if not html == html_orig: #проверка на измененность текста
                bk.writefile(id, html) #запись нового теста в файл
        else:
            print(id_type, id)
    return 0

def main():
    print ("I reached main when I should not have\n")
    return -1
if __name__ == "__main__":
    sys.exit(main())
